# PRIYANSHU

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pwd

'/Users/priyanshupulak/Library/CloudStorage/OneDrive-Personal/Machine Learning A-Z (Codes and Datasets)-2/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python'

In [3]:
ls

Data.csv                           data_preprocessing_template.py
P_dataPreprocessing.ipynb          data_preprocessing_tools.ipynb
Untitled.ipynb                     data_preprocessing_tools.py
data_preprocessing_template.ipynb


In [4]:
dataset = pd.read_csv('Data.csv')

In [5]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
X = dataset.iloc[:, :-1].values # ['rows'(start(0) : end(end - 1)) , 'columns'(start : last - 1)]
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
y = dataset.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# MISSING DATA

In [8]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
 from sklearn.impute import SimpleImputer   # Imputer class --> allows to take care missing data

# making object of imputer class
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') # we can give 'mean, most_frequent' also as s

imputer.fit(X[:, 1:3]) # need to put column which have missing data

X[:, 1:3] = imputer.transform(X[:, 1:3]) # putting the value from imputer to 'NaN'
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Data

In [10]:
'''dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, 3].values'''

"dataset = pd.read_csv('Data.csv')\nX = dataset.iloc[:, :-1].values \ny = dataset.iloc[:, 3].values"

## For Column 1

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
# encoder class ki help se '0' index ko encode kar rha
# remainder --> baki data ko change karne se rokega

X = np.array(ct.fit_transform(X))
# fit_transform --> ki madad se X dataset ko ct object use kar raha

##  For Column  4

In [12]:
from sklearn.preprocessing import LabelEncoder
# LabelEncoder class --> changes string into integer (as we have to do mathematical operations)

labelencoder_y = LabelEncoder() # creating object of LabelEncoder class
y = labelencoder_y.fit_transform(y) # fitting the data in object & change it to integer
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting the Data set into Training Set & Test Set

In [13]:
'''dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, 3].values'''

"dataset = pd.read_csv('Data.csv')\nX = dataset.iloc[:, :-1].values \ny = dataset.iloc[:, 3].values"

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# 80% data is for training the model & 20% for test case

In [15]:
X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [16]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [17]:
y_test

array([0, 0])

In [18]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

# Featuring Scaling

## We need to feature scaling to make all data in same range 

In [19]:
from sklearn.preprocessing import StandardScaler 
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train) # It will first fit the data then transform it
X_test = sc_X.transform(X_test) # from the above fit method used transform the X_test

In [20]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [21]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])